/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ReusedFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TestApi": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
  }
}
